### ISSUE TITLE
Convertation: IResult -> Result

### ISSUE THREAD

**Issue by r4v3n6101** [rust-bakery/nom#1358]
First, thanks for reading. Long time I think about function allows user to convert IResult into Result (assuming we no more need rest of unread data). 
I guess it should look smth like this :
```rust
fn parser<O, E> (input: &[u8]) -> Result<O, E>{
   let parser = ...; // IResult<&[u8], O, E>
   return parser.done(); // or just into() may be? or rewrite existing finish fn?
}
```

**Comment by Stargateur** [comment]
I believe what you want is already implemented with [`finish()`](https://docs.rs/nom/6.2.1/nom/type.IResult.html#method.finish)

Since, we talk about error management in nom, do you think you could tell why you was unable to find this method ?

**Comment by Stargateur** [comment]
Ah I didn't read the comment, don't put important information in comment my brain doesn't bother read them.

I often use this pattern:

```rust
pub fn bearer(input: &str) -> Result<&str, Err<Error<&str>>> {
    let (_, bearer) = combinator::all_consuming(sequence::preceded(
        bytes::tag("Bearer"),
        sequence::preceded(character::space1, b64token),
    ))(input)?;

    Ok(bearer)
}
```

I have a parser for that but for V5:

```rust
pub fn all_consuming<I, O, F, E>(f: F) -> impl Fn(I) -> Result<O, Err<E>>
where
    F: Fn(I) -> IResult<I, O, E> + Copy,
    E: error::ParseError<I>,
    I: nom::InputLength,
{
    move |input| combinator::all_consuming(f)(input).map(|(_, output)| output)
}
```

**Comment by r4v3n6101** [comment]
I can do my own utility, but IMO `Finish` trait should be rewritten or just complemented with new function I described early.

**Comment by Stargateur** [comment]
> I can do my own utility

When did I imply you can't ? why so aggressive to someone who offer a solution ?

> Finish trait should be rewritten or just complemented with new function I described early.

I do not agree cause what you want would not check that all have indeed be consumed, nom is build on the principle of consuming input, and return the rest. If there is some input that remain the parser should not discard it as you proposed.

**Comment by r4v3n6101** [comment]
You misunderstood me, sorry if my words were offensive to you. 
So, sometimes there's a trash data (some formats of files store previous or unused data or pad data or something like this) and we don't need to read rest of data, so we ignore this. 
My idea is to stop parser with data we already parsed and rest isn't meaningful.

**Comment by Stargateur** [comment]
Don't worry, one can use [`rest`](https://docs.rs/nom/6.2.1/nom/combinator/fn.rest.html) to express "discard" in nom and so code would be (using my function) `all_consuming(sequence::preceded(important_parser, rest))` I believe it's more "nomsty".
