### ISSUE TITLE
Support custom containers for `many` functions

### ISSUE THREAD

**Issue by epage** [rust-bakery/nom#1409]
## Prerequisites

Here are a few things you should provide to help me understand the issue:

- Rust version : 1.55.0
- nom version : 7.0.0
- nom compilation features used: default

## Test case

I wanted to experiment with porting `toml_edit` to nom, one thing I especially found missing was custom collection support.  If I use `many0`, it only supports `Vec`.  The naive approach in code is to do
```rust
fn ml_body(input: &str) -> IResult<&str, String> {
    many(substr).map(|s| s.join(""))
}
```
Leading me to allocate a `Vec<String>` and then merge them.  `combine` defaults to `Vec` but allows any `Extend` type, allowing
```rust
fn ml_body(input: &str) -> IResult<&str, String> {
    many(substr)
}
```
which will collect directly into the `String`, saving on a lot of allocations

I'm also looking at optimizing a section of my parser where collect into a `Vec` and then turn it into a `HashMap` with errors by creating a custom type that wraps `HashMap` with my error type and stores off errors on `Extend`, allowing me to bypass the `Vec` allocation.

I could do all of this with `fold_` variants but it will be a bit messier.

**Comment by Stargateur** [comment]
I guess this can be link to #1393.

I think we can use https://doc.rust-lang.org/std/iter/trait.Extend.html to allow this for many.

> I could do all of this with fold_ variants but it will be a bit messier.

You can add your own parser for reuse in the waiting, something like that (I'm more used to nom 6 so probably mistake):
```rust
fn many0_string(f: impl Parser) -> impl Parser {
  |input| {
    fold_many0(
      f,
      String::new,
      |mut acc: String, item| {
        string.push_str(item);
        acc
      }
    )(input)
  }
}
```

> combine defaults to Vec but allows any Extend type, allowing

What is combine ? I don't follow here.

> I'm also looking at optimizing a section of my parser where collect into a Vec and then turn it into a HashMap with errors by creating a custom type that wraps HashMap with my error type and stores off errors on Extend, allowing me to bypass the Vec allocation.

Some sort of [`partition_result()`](https://docs.rs/itertools/0.10.1/itertools/trait.Itertools.html#method.partition_result) ?

**Comment by epage** [comment]
> What is combine ? I don't follow here.

Sorry, `combine` is another parser combinator.

e.g. https://docs.rs/combine/4.6.1/combine/fn.many.html has the collection set to `F: Extend<P::Output> + Default, `

> Some sort of partition_result() ?

More like [`try_fold`](https://doc.rust-lang.org/std/iter/trait.Iterator.html#method.try_fold)

So speaking of, maybe we should have `try_fold_many*` :)

**Comment by Stargateur** [comment]
I fink we can clearly add a `try_fold` and I will try update my PR to include `extend`.

**Comment by Geal** [comment]
oh, using Extend is a great suggestion! I was wondering about doing that too
