### ISSUE TITLE
Take with compile-time count

### ISSUE THREAD

**Issue by r4v3n6101** [rust-bakery/nom#1517]
Hi there. Recently I use nom to parse some bytes as blocks of 32 `u8`. Then I was thinking about `const_take` where we provide count as generic type (iirc it's 1.51 rust release). So, we are able to parse `&[u8; N]`. My implementation does it unsafely however we have guaranties that it won't be unsound: `take` that I call already checks for appropriate count. 

**Pros:**
- allow user get type precisely
- compiler optimization is possible I think (don't really know about it)
- safe at 100%

**Cons:**
- update MSRV to 1.51 at least
- feature may look useless

Prototype of mine:
```rust
fn const_take<const N: usize>(i: &[u8]) -> IResult<&[u8], [u8; N]> {
    // Safety: fine because `take` already check that we took N bytes
    map(take(N), |bytes: &[u8]| unsafe {
        bytes.try_into().unwrap_unchecked()
    })(i)
}
```

**Comment by Xiretza** [comment]
Sure, sounds like it might be useful, but your implementation would actually be unsound for the general (generic) case - [`InputTake`](https://docs.rs/nom/latest/nom/trait.InputTake.html) is safe to implement, so there's nothing stopping an implementation from returning a slice of the wrong size (`take()` doesn't do any checks, contrary to what the Safety comment claims).

**Comment by r4v3n6101** [comment]
The `take` I was talking about is `nom::bytes::complete`, not from `InputTake`. My fault I didn't specify that. 
I don't propose to implement it generally as  `nom::character` module doesn't have any `take`-like combinator like `bytes`. It should be only for bytes I think. 
I agree that `InputTake::take` produces panic if count is greater than length, but `bytes::take` will inform whether provided data was not enough to parse therefore we can't get more than we have. So it should be sound.

**Comment by Xiretza** [comment]
`bytes::complete::take` is just a wrapper around `InputTake::take_split` with not additional checks.

**Comment by r4v3n6101** [comment]
Oh, well, I've got your point. It seems fine for me but we need to take in account that overflowing by `InputTake::take` will panic. So, we have either panic due to incorrect implementation of `InputTake` or exactly N bytes that we take, hence all is correct and sound.
