### ISSUE TITLE
Err` value: Error(())`

### ISSUE THREAD

**Issue by uwejan** [rust-bakery/nom#1589]
I keep getting this error;
`Err` value: Error(())` 
Perhabs am doing something wrong. Please advise.
Thanks in advance.

`parse_string` taken from the [examples](https://github.com/Geal/nom/blob/main/examples/string.rs) 
```
fn main() {
  let dd = "\u{1e}";
  let result = parse_string::<()>(dd);
  println!("Result:\n\n{}", result.unwrap().1);
}
```

**Comment by sshine** [comment]
Since `parse_string()` is supposed to parse string literals (`delimited(char('"'), build_string, char('"'))(input)`), and your `dd` does not have any double quotes inside, I think you are doing something wrong. But I'm not sure exactly what you are trying to do.
