### ISSUE TITLE
`count` panics when parser returns zero-sized `()`

### ISSUE THREAD

**Issue by Shadow53** [rust-bakery/nom#1617]
## Prerequisites

- Rust version : `rustc 1.66.0 (69f9c33d7 2022-12-12)`
- nom version : 7.1.2
- nom compilation features used: default (std)

## Test case

Example test case [(Playground)](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=d67b1d4f394814329a842fde81f9fe67):

```
use nom::{combinator::map, bytes::complete::tag, error::Error, multi::count};

fn main() {
    let parser = map(tag::<_, _, Error<&str>>("abc"), |_| ());
    let result = count(parser, 3)("abcabcabcdef").expect("parsing should succeed");
    println!("{:?}", result);
}
```

Expected: Runs fine, prints:

```
("def", [(), (), ()])
```

Result:

```
Compiling playground v0.0.1 (/playground)
    Finished dev [unoptimized + debuginfo] target(s) in 0.99s
     Running `target/debug/playground`
thread 'main' panicked at 'attempt to divide by zero', /playground/.cargo/registry/src/github.com-1ecc6299db9ec823/nom-7.1.2/src/multi/mod.rs:576:32
note: [run with `RUST_BACKTRACE=1` environment variable to display a backtrace](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=0487bcd80ada6e9943cd7b41b3dcdcbb#)
```

**Comment by w1th0utnam3** [comment]
Hm, that's a regression that can cause breakage (it does for a project of mine). Doesn't this warrant yanking version `7.1.2`?

**Comment by epage** [comment]
While a bug fix is likely warranted, normally crates aren't yanked for regular bugs as yanking can be quite disruptive.

**Comment by Geal** [comment]
yanking is a bit excessive yes, but I'll make a 7.1.3 with that fix

**Comment by Geal** [comment]
[nom 7.1.3](https://crates.io/crates/nom/7.1.3) is published with this fix
