### ISSUE TITLE
Add `is_bin_digit` method

### ISSUE THREAD

**Issue by Chasing1020** [rust-bakery/nom#1652]
## Prerequisites

- Rust version : rustc 1.69.0-nightly (11d96b593 2023-02-01)
- nom version : "7.1.3"

## Question
nom currently provides a set of character test functions like:
[is_digit](https://docs.rs/nom/latest/nom/character/fn.is_digit.html): Tests if byte is ASCII digit: [0-9]
[is_hex_digit](https://docs.rs/nom/latest/nom/character/fn.is_hex_digit.html): Tests if byte is ASCII hex digit: [0-9A-Fa-f]
[is_oct_digit](https://docs.rs/nom/latest/nom/character/fn.is_oct_digit.html): Tests if byte is ASCII octal digit: [0-7]

It appears that there is no method like `is_bin_digit` and `bin_digit0/1` to recognize one or more binary characters: [0-1]. 
At the moment, I am using many1(one_of("01")) to implement this feature, and this will return `Vec<char>`. However, I am not entirely satisfied with this approach. If you have any suggestions for a better method, please let me know. If there are no better solutions, I may consider submitting a pull request at a later time.

**Comment by NickCrews** [comment]
I would vote to keep this feature out, I think it's utility is limited and your current solution does not look that painful.
