### ISSUE TITLE
warning: rejected by a future version of Rust

### ISSUE THREAD

**Issue by calebdiaz** [rust-bakery/nom#1659]
Hello

I'm getting:
warning: the following packages contain code that will be rejected by a future version of Rust: nom v5.1.2
to see what the problems were, use the option `--future-incompat-report`, or run `cargo report future-incompatibilities --id 2`

thanks

**Comment by victorjulien** [comment]
#1657 was opened to address this.

**Comment by Geal** [comment]
nom 5.1.3 and 6.2.2 are now released with a fix for this

**Comment by calebdiaz** [comment]
Thank you very much.
