### ISSUE TITLE
[Feature Request] Pratt Parsing combinators

### ISSUE THREAD

**Issue by stefnotch** [rust-bakery/nom#1690]
Implementing pratt parsing (or precedence climbing, which is supposedly [the same algorithm](https://www.oilshell.org/blog/2016/11/01.html)) could be useful. I quite like it for parsing mathematical expressions with lots of different operators, since I no longer has to bend my parsing rules to fit, and can instead specify the binding power and associativity.

There are other libraries that have implemented this, for example
- https://github.com/kevinmehall/rust-peg#comparison-with-similar-parser-generators
- rust analyzer https://matklad.github.io/2020/04/13/simple-but-powerful-pratt-parsing.html
- chumsky has an experimental one

**Comment by cenodis** [comment]
Duplicate of https://github.com/rust-bakery/nom/issues/1625

**Comment by stefnotch** [comment]
Thanks, then I'll close this one
