### ISSUE TITLE
feature request: Updated documentation to include more relevant Netflow library

### ISSUE THREAD

**Issue by mikemiles-dev** [rust-bakery/nom#1773]
The current documentation/Readme lists https://github.com/dominotree/rs-ipfix for parsing Netflow IPFIX.

There is a newer, more well supported, more downloaded Netflow Parser library that supports not only Version 10 (IPFIX) but also V5, V7, and V9: https://crates.io/crates/netflow_parser https://github.com/mikemiles-dev/netflow_parser

**Comment by mikemiles-dev** [comment]
https://github.com/rust-bakery/nom/pull/1774

**Comment by Geal** [comment]
merged, thanks
